modeloInformacion = [
    {
      RUBROPRESUPEUSTAL: "1 ",
      CONCEPTO: "INGRESOS ",
    },
    {
      RUBROPRESUPEUSTAL: "1.1 ",
      CONCEPTO: "INGRESOS CORRIENTES ",
    },
    {
      RUBROPRESUPEUSTAL: "1.1.02 ",
      CONCEPTO: "INGRESOS NO TRIBUTARIOS ",
    },
    {
      RUBROPRESUPEUSTAL: "1.1.02.01 ",
      CONCEPTO: "CONTRIBUCIONES ",
    },
    {
      RUBROPRESUPEUSTAL: "1.1.02.01.001 ",
      CONCEPTO: "CONTRIBUCIONES SOCIALES ",
    },
    {
      RUBROPRESUPEUSTAL: "1.1.02.01.001.01 ",
      CONCEPTO: "SALUD ",
    },
    {
      RUBROPRESUPEUSTAL: "1.1.02.02 ",
      CONCEPTO: "TASAS Y DERECHOS ADMINISTRATIVOS ",
    },
    {
      RUBROPRESUPEUSTAL: "1.1.02.02.116 ",
      CONCEPTO: "DERECHOS PECUNIARIOS EDUCACION SUPERIOR ",
    },
    {
      RUBROPRESUPEUSTAL: "1.1.02.03",
      CONCEPTO: "MULTAS, SANCIONES E INTERESES DE MORA ",
    },
    {
      RUBROPRESUPEUSTAL: "1.1.02.03.001 ",
      CONCEPTO: "MULTAS Y SANCIONES ",
    },
    {
      RUBROPRESUPEUSTAL: "1.1.02.05 ",
      CONCEPTO: "VENTA DE BIENES Y SERVICIOS ",
    },
    {
      RUBROPRESUPEUSTAL: "1.1.02.05.001 ",
      CONCEPTO: "VENTAS DE ESTABLECIMIENTOS DE MERCADO ",
    },
    {
      RUBROPRESUPEUSTAL: "1.1.02.05.001.08 ",
      CONCEPTO: "SERVICIOS PRESTADOS A LAS EMPRESAS Y SERVICIOS DE PRODUCCION  ",
    },
    {
      RUBROPRESUPEUSTAL: "1.1.02.05.001.09 ",
      CONCEPTO: "SERVICIOS PARA LA COMUNIDAD, SOCIALES Y PERSONALES "
    },
    {
      RUBROPRESUPEUSTAL: "1.1.02.05.002 ",
      CONCEPTO: "VENTAS INCIDENTALES DE ESTABLECIMIENTOS NO DE MERCADO ",
    },
    {
      RUBROPRESUPEUSTAL: "1.1.02.05.002.03 ",
      CONCEPTO: "OTROS BIENES TRANSPORTABLES EXCEPTO PRODUCTOS METALICOS, MAQUINARIA Y EQUIPO ",
    },
    {
      RUBROPRESUPEUSTAL: "1.1.02.06 ",
      CONCEPTO: "TRANSFERENCIAS CORRIENTES ",
    },
    {
      RUBROPRESUPEUSTAL: "1.1.02.06.006 ",
      CONCEPTO: "TRANSFERENCIAS DE OTRAS ENTIDADES DEL GOBIERNO GENERAL ",
    },
    {
      RUBROPRESUPEUSTAL: "1.1.02.06.009.02 ",
      CONCEPTO: "SISTEMA GENERAL DE PENSIONES ",
    },
    {
      RUBROPRESUPEUSTAL: "1.2 ",
      CONCEPTO: "RECURSOS DE CAPITAL ",
    },
    {
      RUBROPRESUPEUSTAL: "1.2.01 ",
      CONCEPTO: "DISPOSICION DE ACTIVOS ",
    },
    {
      RUBROPRESUPEUSTAL: "1.2.01.02 ",
      CONCEPTO: "DISPOSICION DE ACTIVOS NO FINANCIEROS ",
    },
    {
      RUBROPRESUPEUSTAL: "1.2.01.02.001 ",
      CONCEPTO: "DISPOSICION DE ACTIVOS FIJOS ",
    },
    {
      RUBROPRESUPEUSTAL: "1.2.05 ",
      CONCEPTO: "RENDIMIENTOS FINANCIEROS ",
    },
    {
      RUBROPRESUPEUSTAL: "1.2.05.02 ",
      CONCEPTO: "DEPOSITOS ",
    },
    {
      RUBROPRESUPEUSTAL: "1.2.08 ",
      CONCEPTO: "TRANSFERENCIAS DE CAPITAL ",
    },
    {
      RUBROPRESUPEUSTAL: "1.2.08.01 ",
      CONCEPTO: "DONACIONES ",
    },
    {
      RUBROPRESUPEUSTAL: "1.2.08.01.003 ",
      CONCEPTO: "DEL SECTOR PRIVADO ",
    },
    {
      RUBROPRESUPEUSTAL: "1.2.08.02 ",
      CONCEPTO: "INDEMNIZACIONES RELACIONADAS CON SEGUROS NO DE VIDA "
    },
    {
      RUBROPRESUPEUSTAL: "1.2.10 ",
      CONCEPTO: "RECURSOS DEL BALANCE ",
    },
    {
      RUBROPRESUPEUSTAL: "1.2.10.02 ",
      CONCEPTO: "SUPERAVIT FISCAL "
    },
    {
      RUBROPRESUPEUSTAL: "1.2.13 ",
      CONCEPTO: "REINTEGROS Y OTROS RECURSOS NO APROPIADOS ",
    },
    {
      RUBROPRESUPEUSTAL: "1.2.13.01 ",
      CONCEPTO: "REINTEGROS "
    }
  ]